config/routes.rb
Rails.application.routes.draw do
  get 'filter_movie/index'
  resources :rates
  resources :genres
  resources :movies
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :movies
    validates :title_genre, presence: true, length: (2..30)
    validates :description_genre, length: (140..280)

end

app/models/movie.rb
class Movie < ApplicationRecord
    belongs_to :genre 
    belongs_to :rate

    def runtime_hour(hour)
        "#{hour/60}h #{hour % 60}min"
    end
end

app/models/rate.rb
class Rate < ApplicationRecord
    has_many :movies
    validates :score, presence: true,  numericality: {in: (1..100)}
    validates :commentary, length: (140..280)

    def classify_rate(rate)
        classification = {0..30 => "bad",31..60 => "regular", 61..80 => "good", 81..100 => "must-see"}
        classification.select{|range| range === rate}.values.first
    end
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/filter_movie_controller.rb
class FilterMovieController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[ show edit update destroy ]

  # GET /genres or /genres.json
  def index
    @genres = Genre.all
    @movies = Movie.all
  end

  # GET /genres/1 or /genres/1.json
  def show
    @movies = Movie.all
    @i = 0
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to genre_url(@genre), notice: "Genre was successfully created." }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to genre_url(@genre), notice: "Genre was successfully updated." }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url, notice: "Genre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.require(:genre).permit(:title_genre, :description_genre)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all.sort_by{|a| a.title}
    @i = 0
  end

  # GET /movies/1 or /movies/1.json
  def show
    session[:movie] = @movie
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :resume, :release_year, :runtime, :url_poster, :url_large_image)
    end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_rate, only: %i[ show edit update destroy ]

  # GET /rates or /rates.json
  def index
    @rates = Rate.all
  end

  # GET /rates/1 or /rates/1.json
  def show
    @movie = session[:movie]
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates or /rates.json
  def create
    @rate = Rate.new(rate_params)

    respond_to do |format|
      if @rate.save
        format.html { redirect_to rate_url(@rate), notice: "Rate was successfully created." }
        format.json { render :show, status: :created, location: @rate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1 or /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to rate_url(@rate), notice: "Rate was successfully updated." }
        format.json { render :show, status: :ok, location: @rate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1 or /rates/1.json
  def destroy
    @rate.destroy

    respond_to do |format|
      format.html { redirect_to rates_url, notice: "Rate was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rate_params
      params.require(:rate).permit(:score, :commentary, :time_rate)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @movies = Movie.all
    @movie 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filter_movie_helper.rb
module FilterMovieHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
    def runtime_hour(hour)
        "#{hour/60}h #{hour % 60}min"
    end

    def number_movie(movie)
        number = number + 1
    end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
    def truncate_text (text)
        text.first(150)+"..."
    end
    def class_rate(rate)
        rates_rate = {0..30 => "bg-danger",31..60 => "bg-warning", 60..100 => "bg-success"}
        rates_rate.select{|range| range === rate}.values.first
    end
end

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |form| %>
  <% if genre.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title_genre, style: "display: block" %>
    <%= form.text_field :title_genre %>
  </div>

  <div>
    <%= form.label :description_genre, style: "display: block" %>
    <%= form.text_area :description_genre %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/_genre.html.erb
<div id="<%= dom_id genre %>">
  <h1><%= genre.title_genre%></h1>
  <div class="d-flex">
    <% @movies.select{|movie| movie.genre.title_genre.include? genre.title_genre}.first(3).each do |movie|%>
      <div class="mx-3">
        <%= link_to (image_tag movie.url_poster, width:156, height:231), movie %>
      </div>
    <% end %>
    <p class="text-center"><%=genre.description_genre%><%= link_to "Veja mais filmes de #{genre.title_genre}", genre %></p>
  </div>
</div>

app/views/genres/edit.html.erb
<h1>Editing genre</h1>

<%= render "form", genre: @genre %>

<br>

<div>
  <%= link_to "Show this genre", @genre %> |
  <%= link_to "Back to genres", genres_path %>
</div>

app/views/genres/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Genres</h1>

<div id="genres">
  <% @genres.each do |genre| %>
    <%= render genre %>
    <hr>
  <% end %>
</div>

app/views/genres/new.html.erb
<h1>New genre</h1>

<%= render "form", genre: @genre %>

<br>

<div>
  <%= link_to "Back to genres", genres_path %>
</div>

app/views/genres/show.html.erb
<p style="color: green"><%= notice %></p>

<section>
  <div class="container">
    <h3 class="text-center"><%= @genre.title_genre%></h3>
    <p class="text-center fs-6"><%= @genre.description_genre%></p>
    
    <div class="mb-5 d-flex align-items-center">
      <p class="mx-2">Filtros:</p>
      <%= button_tag "ano de lançamento", type: 'button', onclick:"myFunction('lancamento')" , class: 'btn bg-success mx-2 text-white' %>
      <%= button_tag "avaliacao", type: 'button', onclick: "myFunction('avaliacao')", class: 'btn bg-success mx-2 text-white' %>
      <%= button_tag "nome", type: 'button', onclick: "myFunction('name')", class: 'btn bg-success mx-2 text-white' %>
    </div>
    <ul class="row row-cols-6 text-center list-movies" id="movies">
      <% @movies.select{|movie| movie.genre.title_genre.include? @genre.title_genre}.each do |movie|%>      
        <%= render movie %>
      <% end %>
    </ul>
  <%= link_to "Back to genres", genres_path, class: "btn btn-success text-center"%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sabe Aquele Filme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header><%= render "partials/menu_bar" %></header>
    <%= yield %>
    <footer><%= render "partials/footer" %></footer>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :resume, style: "display: block" %>
    <%= form.text_area :resume %>
  </div>

  <div>
    <%= form.label :release_year, style: "display: block" %>
    <%= form.number_field :release_year %>
  </div>

  <div>
    <%= form.label :runtime, style: "display: block" %>
    <%= form.number_field :runtime %>
  </div>

  <div>
    <%= form.label :url_poster, style: "display: block" %>
    <%= form.text_field :url_poster %>
  </div>

  <div>
    <%= form.label :url_large_image, style: "display: block" %>
    <%= form.text_field :url_large_image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<li 
  class="col mx-3 my-3 position-relative" 
  style="list-style:none" 
  id="<%= dom_id movie %>"
  data-lancamento=<%= movie.release_year%>
  data-avaliacao=<%= movie.rate.score%>
  data-name=<%= @i = @i + 1%>>

  <div class="position-absolute px-3 py-2 top-0 start-70 translate-middle badge <%= class_rate movie.rate.score%>"><h6><%= movie.rate.score%></h6></div>
  <%= link_to (image_tag movie.url_poster, width:115, height:155), movie, class: "link_movie_#{movie.id}"%>
  <p class="text-center">
    <strong><%= movie.title %></strong><br>
    <%= movie.release_year %>
  </p>  
</li>

app/views/movies/_showMovie.html.erb
<div id="<%= dom_id movie %>">
    <div>
        <%= image_tag movie.url_large_image%>
    </div>
    <div>
        <div>
            <%= image_tag movie.url_poster%>
        </div>
        <div>
            <p><%= movie.resume %></p>
        </div>
    </div>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movies</h1>
<section class="mb-5 d-flex align-items-center" >
  <p class="mx-2">Filtros:</p>
  <%= button_tag "ano de lançamento", type: 'button', onclick:"myFunction('lancamento')" , class: 'btn bg-success mx-2' %>
  <%= button_tag "avaliacao", type: 'button', onclick: "myFunction('avaliacao')", class: 'btn bg-success mx-2' %>
  <%= button_tag "nome", type: 'button', onclick: "myFunction('name')", class: 'btn bg-success mx-2' %>

</section>
<section>
  <ul class="row row-cols-6 text-center list-movies" id="movies">
    <% @movies.each do |movie| %>
      <%= render movie %>
    <% end %>
  </ul>
</section>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="<%= dom_id @movie %>">
  <div class="w-100 mb-5">
      <%= image_tag @movie.url_large_image, width: "100%", height: "650px", class: "opacity-50"%>
  </div>
  <div class="d-flex align-items-center px-5">
    <%= image_tag @movie.url_poster%>
    <div class="px-4">
        <h3><%= @movie.title%> (<%= @movie.release_year%>)</h3>
        <p><%= runtime_hour @movie.runtime %></p>
        <p class="fs-5 text-justify"><%= @movie.resume %></p>
    </div>
   <div class="badge <%= class_rate @movie.rate.score%> fs-2 h-25">
      <%= @movie.rate.score%>
   </div>
</div>
<div class="d-flex mt-5 justify-content-center">
  <%= link_to "Back to movies", movies_path, class: "btn btn-success mx-2"%>
  <%= link_to "Veja a avaliacação para #{@movie.title}", rate_path , class: "btn btn-success mx-3" %>

</div>

app/views/partials/_footer.html.erb
<footer class="h-50 bg-primary text-center">
    <small class="">Criado por Victor Hugo Moreira</small>
</footer>

app/views/partials/_menu_bar.html.erb
<header>
    <nav class="d-flex justify-content-between px-2 navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav mr-auto">
            <%= link_to "Sabe Aquele Filme", welcome_index_path, class:"nav-link"  %>
            <li class="nav-item active">
                <%= link_to "Home", welcome_index_path, class:"nav-link"  %>
            </li>
            <li class="nav-item active">
                <%= link_to "Filmes", movies_path, class:"nav-link"  %>
            </li>
            <li class="nav-item active">
                <%= link_to "Generos", genres_path, class:"nav-link"  %>
            </li>
        </ul>
        <p>
            <%= link_to "Português", "/?locale=pt-BR" %>
            <%= link_to "English", "/?locale=en" %>
        </p>
    </nav>
    
</header>

app/views/rates/_form.html.erb
<%= form_with(model: rate) do |form| %>
  <% if rate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
        <% rate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :score, style: "display: block" %>
    <%= form.number_field :score %>
  </div>

  <div>
    <%= form.label :commentary, style: "display: block" %>
    <%= form.text_area :commentary %>
  </div>

  <div>
    <%= form.label :time_rate, style: "display: block" %>
    <%= form.datetime_field :time_rate %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rates/_rate.html.erb
<div id="<%= dom_id rate %>">
  <p>
    <strong>Score:</strong>
    <%= rate.score %>
  </p>

  <p>
    <strong>Commentary:</strong>
    <%= rate.commentary %>
  </p>

  <p>
    <strong>Time rate:</strong>
    <%= rate.time_rate %>
  </p>

</div>

app/views/rates/edit.html.erb
<h1>Editing rate</h1>

<%= render "form", rate: @rate %>

<br>

<div>
  <%= link_to "Show this rate", @rate %> |
  <%= link_to "Back to rates", rates_path %>
</div>

app/views/rates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rates</h1>

<div id="rates">
  <% @rates.each do |rate| %>
    <%= render rate %>
    <p>
      <%= link_to "Show this rate", rate %>
    </p>
  <% end %>
</div>

<%= link_to "New rate", new_rate_path %>

app/views/rates/new.html.erb
<h1>New rate</h1>

<%= render "form", rate: @rate %>

<br>

<div>
  <%= link_to "Back to rates", rates_path %>
</div>

app/views/rates/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card w-75 container">
  <div class="card-body text-center py-2">
    <div class="badge bg-success h-75 p-4 mt-4 mx-2 fs-3 float-start"><%= @rate.score %></div>
    <h5 class="card-title"><%= @movie['title']%></h5>
    <p class="card-text text-justify text-dark"><strong>Commentary: </strong><%= @rate.commentary%></p>
    <%= link_to "Back to #{@movie['title']}", "/movies/#{@movie["id"]}", class: "btn btn-success" %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="text-center banner">
    <h1>Sabe Aquele Filme</h1>
</div>
<div class="d-grid gap-4 col-5 mx-auto text-center">
    <h3 class="text-center">Acompanhe os filmes que você assistiu.</h3>
    <h3 class="text-center">Salve aqueles que você deseja ver.</h3>
    <h3 class="text-center">Diga a seus amigos o que é bom.</h3>
    <%= link_to "Veja Mais", movies_path, class: "btn btn-success px-5" %>
</div>

    <div class="container mt-5 list-movie" id="new_movies">
        <div class="row" id="movie_list">
            <% @movies.sort_by{|movie| movie.release_year}.filter{|movie| movie.release_year > 2020}.first(6).reverse.each do |movie| %>
                <div class="col px-2 movie" id="<%= dom_id movie%>" data-release_year = <%=movie.release_year%>>
                    <div class="tip">
                        <small class="tiptext"><%= movie.title %><br><%= movie.release_year%></small>
                    </div>
                    <%= link_to (image_tag movie.url_poster, width:170, height:250, class:"rounded-2 new_movie" ), movie %>
                </div>
            <% end %>
        </div>
    </div>
<br>
<section class="mt-5">
    <h1 class="text-center mb-5">Ultimos filmes avaliados</h1>
    <ul class="container">
    <% @movies.filter{|movie| movie.rate.time_rate > Time.new(2023)}.first(5).each do |movie| %>
        <li class="d-flex justify-content-center mb-4 movies_avaliados">
            <%= link_to (image_tag movie.url_poster, width:100, height:150, class: "mx-2"), movie %>
            <div class="mx-2">
                <h3><%= movie.title%></h3><small class="badge bg-primary"><%= movie.release_year%></small>
                <p class="pt-2"><%= truncate_text(movie.rate.commentary)%><%= link_to "Veja a critica completa", "/rates/#{movie.rate.id}"%></p>
            </div>
            <div class="badge <%= class_rate movie.rate.score%> fs-3" style="height:50px">
                <%= movie.rate.score%>
            <div> 
        </li>   
        <hr>
        <% end %>
    </ul>
</section>